export const tasks = [
  {
    ID: 1,
    Task: 'Complete project documentation',
    Priority: 'High',
    Status: 'In Progress',
  },
  {
    ID: 2,
    Task: 'Fix UI bugs in the dashboard',
    Priority: 'Medium',
    Status: 'Not started',
  },
  {
    ID: 3,
    Task: 'Implement authentication module',
    Priority: 'High',
    Status: 'Completed',
  },
  {
    ID: 4,
    Task: 'Optimize database queries',
    Priority: 'High',
    Status: 'In Progress',
  },
  {
    ID: 5,
    Task: 'Design new landing page',
    Priority: 'Low',
    Status: 'Not started',
  },
  {
    ID: 6,
    Task: 'Refactor API endpoints',
    Priority: 'Medium',
    Status: 'Completed',
  },
  {
    ID: 7,
    Task: 'Conduct user testing',
    Priority: 'High',
    Status: 'Not started',
  },
  {
    ID: 8,
    Task: 'Write unit tests for services',
    Priority: 'Medium',
    Status: 'In Progress',
  },
  {
    ID: 9,
    Task: 'Deploy latest release',
    Priority: 'High',
    Status: 'Not started',
  },
  {
    ID: 10,
    Task: 'Monitor system performance',
    Priority: 'Low',
    Status: 'In Progress',
  },
  {
    ID: 11,
    Task: 'Complete project ',
    Priority: 'High',
    Status: 'In Progress',
  },
  {
    ID: 12,
    Task: 'Fix UI bugs in the ',
    Priority: 'Medium',
    Status: 'Not started',
  },
  {
    ID: 13,
    Task: 'Implement  module',
    Priority: 'High',
    Status: 'Completed',
  },
  {
    ID: 14,
    Task: 'Optimize database ',
    Priority: 'High',
    Status: 'In Progress',
  },
  {
    ID: 15,
    Task: 'Design new landing ',
    Priority: 'Low',
    Status: 'Not started',
  },
  {
    ID: 16,
    Task: 'Refactor API ',
    Priority: 'Medium',
    Status: 'Completed',
  },
  {
    ID: 17,
    Task: 'Conduct user ',
    Priority: 'High',
    Status: 'Not started',
  },
  {
    ID: 18,
    Task: 'Write unit tests ',
    Priority: 'Medium',
    Status: 'In Progress',
  },
  {
    ID: 19,
    Task: 'Deploy latest ',
    Priority: 'High',
    Status: 'Not started',
  },
  {
    ID: 20,
    Task: 'Monitor system ',
    Priority: 'Low',
    Status: 'In Progress',
  },
];
